[project]
name = "virtual-shell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
]

# Console script to start the shell
[project.scripts]
virtual-shell = "virtual_shell.main:main"
snapshot-cli = "virtual_shell.cli.snapshot_cli:main"
filesystem-template-cli = "virtual_shell.cli.filesystem_template_cli:main"

[dependency-groups]
dev = [
    "pytest-asyncio>=0.26.0",
    "pytest>=8.3.5",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.hatch.build.targets.wheel]
packages = ["virtual_shell"]
