# AI Sandbox configuration for PyodideShell
# Restricted environment for AI code execution

# Sandbox name and description
name: "ai_sandbox"
description: "Restricted environment for AI code execution"

# Security settings
security:
  profile: "untrusted"    # Using the untrusted security profile
  read_only: false        # Allow writing within restricted areas
  max_file_size: 1048576  # 1MB max file size
  max_total_size: 10485760 # 10MB total storage quota
  max_files: 100          # Maximum number of files
  max_path_depth: 3       # Maximum path depth
  allowed_paths:          # Only allow access to the sandbox directory
    - "/sandbox"
  denied_paths:           # Explicitly deny access to these critical system paths
    - "/etc"
    - "/bin"
    - "/home"
    - "/usr"
  # Denied patterns (these strings will be converted to regex objects in the code)
  denied_patterns:
    - "\\.\\."            # Prevent directory traversal (e.g., ../)
    - "^\\."              # Block hidden files (starting with a dot)
    - ".*\\.(exe|sh|bat|cmd)$"  # Block executable files

# Filesystem provider settings
filesystem:
  provider: "memory"      # Provider to use (e.g., memory, sqlite, etc.)
  provider_args: {}       # Additional arguments for the provider (empty by default)

# Environment variables (values should be consistent with security and allowed paths)
environment:
  HOME: "/sandbox"
  PATH: "/bin"           # Note: Ensure PATH is safe in conjunction with denied_paths
  USER: "ai"
  SHELL: "/bin/bash"
  TERM: "xterm"
  SANDBOX_MODE: "restricted"

# Initialization commands (executed during setup in order)
initialization:
  - "mkdir -p /sandbox/input"
  - "mkdir -p /sandbox/output"
  - "echo 'AI Sandbox - Restricted Environment' > /sandbox/README.txt"
  - "echo 'Use /sandbox/input for input files and /sandbox/output for results.' > /sandbox/USAGE.txt"
